<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="scara_robot">

    <!-- \\\\\\ Build 2DoF Arm Robot \\\\\\ -->

    <!-- \\\ Include Parameters and Macros \\\ -->
    <xacro:include filename="$(find scara_robot)/models/params_macro.xacro"/>

    <!-- Chassis Link: Fictitious Link -->
    <link name = "world"/>

    <joint name="world_joint" type="fixed">
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
        <parent link="world"/>
        <child link="base"/>
    </joint>

    <!--Base-->
    <xacro:cylinder_link name="base" length="${base_height}" radius="${base_width/2}" 
                            mass="${m_base}" colour="Black"/>

    <!--Arm 1-->
    <xacro:scara_arm name="arm1" scale_x="${scalex_1}" mass="${m1}" colour="White"/>

    <!-- Joint 1-->
    <joint name="joint_1" type="continuous">
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <parent link="base"/>
        <child link="arm1"/>
        <axis xyz="0 0 1"/>
        <limit effort="${joint_effort}" velocity="${joint_vel}"/>
        <dynamics damping="1.0"/>
    </joint>

    <!--Arm 2-->
    <xacro:scara_arm name="arm2" scale_x="${scalex_2}" mass="${m2}" colour="Red"/>
    
    <!-- Joint 2-->
    <joint name="joint_2" type="continuous">
        <origin xyz="${(scalex_1 * arm_dist_rot)} 0 ${arm_height}" rpy="0 0 0"/>
        <parent link="arm1"/>
        <child link="arm2"/>
        <axis xyz="0 0 1"/>
        <limit effort="${joint_effort}" velocity="${joint_vel}"/>
        <dynamics damping="1.0"/>
    </joint>

    <!--Linear needle-->
    <xacro:cylinder_link name="lin" length="${(base_height + 2*arm_height)}" radius="${r3}" z="${(base_height + 2*arm_height)/2}"
                            mass="${m3}" colour="Green"/>



    <!-- Joint 3 (linear)
        origon of joint set to ZERO, therefore controller input equals absolute z-position -->
    <joint name="joint_3" type="prismatic">
    <origin xyz="${(scalex_2 * arm_dist_rot)} 0 ${-(base_height + arm_height)}" rpy="0 0 0"/>
    <parent link="arm2"/>
    <child link="lin"/>
    <axis xyz="0 0 1"/>
    <limit effort="${joint_effort}" velocity="${joint_vel}" lower="0" upper="${(base_height + arm_height)}"/>
    <dynamics damping="1.0"/>
    </joint>


    <!-- \\\ Actuation \\\ -->
    <xacro:transmission_block joint_name="joint_1" location="1"/>
    <xacro:transmission_block joint_name="joint_2" location="2"/>
    <xacro:transmission_block joint_name="joint_3" location="3"/>

    <!-- \\\\\\ GAZEBO Plugins \\\\\\ -->
    <!-- ros_control plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/scara_robot</robotNamespace>
        </plugin>
    </gazebo>

    <!-- IMU Plugins -->
    <link name="imu_link">
        <inertial>
            <mass value="${imu_mass}"/>
            <inertia ixx="${imu_ixx}" ixy="0.0" ixz="0.0"
                            iyy="${imu_iyy}" iyz="0.0" izz="${imu_izz}"/>

            <origin xyz="0 0 0" rpy="0 0 0"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${imu_size} ${imu_size} ${imu_size}"/>
            </geometry>
        </visual>
        
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${imu_size} ${imu_size} ${imu_size}"/>
            </geometry>
        </collision>
    </link>

    <joint name="imu_joint" type="fixed">
        <axis xyz="1 0 0"/> <!-- 0 1 0 -->
        <origin xyz="0 0 0"/>
        <parent link="lin"/>
        <child link="imu_link"/>
    </joint>

    <!-- IMU inherit Sensor Plugin-->
    <gazebo reference="imu_link">
        <gravity>true</gravity>

        <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>${imu_freq}</update_rate>
            <visualize>true</visualize>
            <topic>__default_topic__</topic>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>/scara_robot/imu</topicName>
                <bodyName>imu_link</bodyName>
                <updateRateHZ>${imu_freq}</updateRateHZ>
                <gaussianNoise>${imu_noise}</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset>
                <frameName>imu_link</frameName>
                <initialOrientationAsReference>false</initialOrientationAsReference>
            </plugin>
            <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo>
</robot>
